/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.pedrohubner.pocdeliverysubsidiaryservice;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        final var sumResult = App.sum(1, 2);
        Assertions.assertEquals(3, sumResult);
    }

    @Test
    public void testMain() {
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));
        git remote add origin https://github.com/pedrohubner/pic-delivery-subsidiary-service.git
        App.main(new String[]{});

        String expectedOutput = "Hello World!3" + System.lineSeparator();
        assertEquals(expectedOutput, outContent.toString());
    }

}
